version: "3"

services:
  userservice:
    container_name: userservice
    env_file: ../envs/.env.development
    build:
      context: ../user-service
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - elasticsearch
    restart: unless-stopped

  bookservice:
    container_name: bookservice
    env_file: ../envs/.env.development
    build:
      context: ../book-service
      dockerfile: Dockerfile
    ports:
      - "${BOOK_SERVICE_PORT}:${BOOK_SERVICE_PORT}"
    depends_on:
      - mysql
      - userservice
      - redis
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.5
    volumes:
      - ./kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  redis:
    container_name: redis
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: "12345678"
    volumes:
      - "./mysql/db:/var/lib/mysql"
    restart: unless-stopped

